import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import dotenv from 'dotenv';

dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('SUPABASE_URL or SUPABASE_KEY missing in .env');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

function sqlEscape(val) {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number') return val;
  if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
  if (typeof val === 'object') {
    return "'" + JSON.stringify(val).replace(/'/g, "''") + "'::jsonb";
  }
  return "'" + String(val).replace(/'/g, "''") + "'";
}

async function exportAll() {
  console.log('Fetching all tables from source Supabase:', supabaseUrl);

  const users = (await supabase.from('users').select('*').order('id')).data || [];
  const categories = (await supabase.from('categories').select('*').order('id')).data || [];
  const tasks = (await supabase.from('tasks').select('*').order('id')).data || [];
  const sub_units = (await supabase.from('sub_units').select('*').order('id')).data || [];
  const marble_distribution = (await supabase.from('marble_distribution').select('*').order('id')).data || [];
  const daily_updates = (await supabase.from('daily_updates').select('*').order('id')).data || [];
  const materials_consumption = (await supabase.from('materials_consumption').select('*').order('created_at')).data || [];

  console.log(`Fetched counts:
- users: ${users.length}
- categories: ${categories.length}
- tasks: ${tasks.length}
- sub_units: ${sub_units.length}
- marble_distribution: ${marble_distribution.length}
- daily_updates: ${daily_updates.length}
- materials_consumption: ${materials_consumption.length}`);

  let sql = `-- ========================================================\n`;
  sql += `-- SUPABASE COMPLETE DATABASE BACKUP & MIGRATION SCRIPT\n`;
  sql += `-- Export Date: ${new Date().toISOString()}\n`;
  sql += `-- Source Project URL: ${supabaseUrl}\n`;
  sql += `-- ========================================================\n\n`;

  sql += `-- 1. DROP EXISTING VIEWS AND TABLES\n`;
  sql += `DROP VIEW IF EXISTS public.daily_updates_with_users CASCADE;\n`;
  sql += `DROP VIEW IF EXISTS public.sub_units_stats CASCADE;\n`;
  sql += `DROP TABLE IF EXISTS public.materials_consumption CASCADE;\n`;
  sql += `DROP TABLE IF EXISTS public.daily_updates CASCADE;\n`;
  sql += `DROP TABLE IF EXISTS public.marble_distribution CASCADE;\n`;
  sql += `DROP TABLE IF EXISTS public.sub_units CASCADE;\n`;
  sql += `DROP TABLE IF EXISTS public.tasks CASCADE;\n`;
  sql += `DROP TABLE IF EXISTS public.categories CASCADE;\n`;
  sql += `DROP TABLE IF EXISTS public.users CASCADE;\n\n`;

  sql += `-- 2. CREATE TABLES WITH EXACT SCHEMAS\n\n`;

  // Users
  sql += `CREATE TABLE public.users (\n`;
  sql += `    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n`;
  sql += `    email TEXT NOT NULL UNIQUE,\n`;
  sql += `    password TEXT NOT NULL,\n`;
  sql += `    name TEXT,\n`;
  sql += `    role TEXT\n`;
  sql += `);\n\n`;

  // Categories
  sql += `CREATE TABLE public.categories (\n`;
  sql += `    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n`;
  sql += `    name TEXT NOT NULL\n`;
  sql += `);\n\n`;

  // Tasks
  sql += `CREATE TABLE public.tasks (\n`;
  sql += `    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n`;
  sql += `    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,\n`;
  sql += `    name TEXT NOT NULL,\n`;
  sql += `    total_quantity NUMERIC,\n`;
  sql += `    completed_quantity NUMERIC,\n`;
  sql += `    progress_percent NUMERIC,\n`;
  sql += `    unit TEXT,\n`;
  sql += `    notes TEXT,\n`;
  sql += `    is_manual INT DEFAULT 1\n`;
  sql += `);\n\n`;

  // Sub Units
  sql += `CREATE TABLE public.sub_units (\n`;
  sql += `    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n`;
  sql += `    task_id BIGINT REFERENCES public.tasks(id) ON DELETE CASCADE,\n`;
  sql += `    serial_number INT,\n`;
  sql += `    zone TEXT,\n`;
  sql += `    code TEXT,\n`;
  sql += `    status TEXT,\n`;
  sql += `    total_quantity INT DEFAULT 1,\n`;
  sql += `    notes TEXT,\n`;
  sql += `    white_marked INT DEFAULT 0,\n`;
  sql += `    white_extra INT DEFAULT 0,\n`;
  sql += `    white_applied INT DEFAULT 0,\n`;
  sql += `    white_date TEXT DEFAULT '',\n`;
  sql += `    brown_marked INT DEFAULT 0,\n`;
  sql += `    brown_extra INT DEFAULT 0,\n`;
  sql += `    brown_applied INT DEFAULT 0,\n`;
  sql += `    brown_date TEXT DEFAULT ''\n`;
  sql += `);\n\n`;

  // Marble Distribution
  sql += `CREATE TABLE public.marble_distribution (\n`;
  sql += `    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n`;
  sql += `    zone TEXT,\n`;
  sql += `    task_name TEXT,\n`;
  sql += `    white_qty INT,\n`;
  sql += `    brown_qty INT,\n`;
  sql += `    status TEXT\n`;
  sql += `);\n\n`;

  // Daily Updates
  sql += `CREATE TABLE public.daily_updates (\n`;
  sql += `    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n`;
  sql += `    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,\n`;
  sql += `    sender_name TEXT,\n`;
  sql += `    sender_role TEXT,\n`;
  sql += `    message_text TEXT,\n`;
  sql += `    media_url TEXT,\n`;
  sql += `    media_type TEXT,\n`;
  sql += `    reply_to_id BIGINT REFERENCES public.daily_updates(id) ON DELETE SET NULL,\n`;
  sql += `    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())\n`;
  sql += `);\n\n`;

  // Materials Consumption
  sql += `CREATE TABLE public.materials_consumption (\n`;
  sql += `    id TEXT PRIMARY KEY,\n`;
  sql += `    date TEXT NOT NULL,\n`;
  sql += `    day TEXT,\n`;
  sql += `    start_time TEXT,\n`;
  sql += `    end_time TEXT,\n`;
  sql += `    prepared_by TEXT,\n`;
  sql += `    basics JSONB,\n`;
  sql += `    marble JSONB,\n`;
  sql += `    sealants JSONB,\n`;
  sql += `    bulk JSONB,\n`;
  sql += `    notes TEXT,\n`;
  sql += `    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())\n`;
  sql += `);\n\n`;

  // Views
  sql += `-- 3. CREATE VIEWS\n`;
  sql += `CREATE OR REPLACE VIEW public.sub_units_stats AS\n`;
  sql += `SELECT zone, status, COUNT(*)::INT as count\n`;
  sql += `FROM public.sub_units\n`;
  sql += `GROUP BY zone, status;\n\n`;

  sql += `CREATE OR REPLACE VIEW public.daily_updates_with_users AS\n`;
  sql += `SELECT \n`;
  sql += `    d.id, d.user_id, d.sender_name, d.sender_role, d.message_text, d.media_url, d.media_type, d.reply_to_id, d.created_at,\n`;
  sql += `    u.name as user_name, u.role as user_role,\n`;
  sql += `    r.sender_name as reply_sender_name, r.message_text as reply_message_text, r.media_url as reply_media_url, r.media_type as reply_media_type\n`;
  sql += `FROM public.daily_updates d\n`;
  sql += `LEFT JOIN public.users u ON d.user_id = u.id\n`;
  sql += `LEFT JOIN public.daily_updates r ON d.reply_to_id = r.id;\n\n`;

  // Row Level Security & Policies
  sql += `-- 4. ROW LEVEL SECURITY (RLS) POLICIES\n`;
  const allTables = ['users', 'categories', 'tasks', 'sub_units', 'marble_distribution', 'daily_updates', 'materials_consumption'];
  for (const table of allTables) {
    sql += `ALTER TABLE public.${table} ENABLE ROW LEVEL SECURITY;\n`;
    sql += `DROP POLICY IF EXISTS "Allow public operations on ${table}" ON public.${table};\n`;
    sql += `CREATE POLICY "Allow public operations on ${table}" ON public.${table} FOR ALL USING (true) WITH CHECK (true);\n`;
  }
  sql += `\n`;

  // Data Inserts
  sql += `-- 5. INSERT DATA (${users.length} users, ${categories.length} categories, ${tasks.length} tasks, ${sub_units.length} sub_units, ${marble_distribution.length} marble_distribution, ${daily_updates.length} daily_updates, ${materials_consumption.length} materials_consumption)\n\n`;

  // Users
  for (const u of users) {
    sql += `INSERT INTO public.users (id, email, password, name, role) VALUES (${u.id}, ${sqlEscape(u.email)}, ${sqlEscape(u.password)}, ${sqlEscape(u.name)}, ${sqlEscape(u.role)});\n`;
  }
  sql += `SELECT setval(pg_get_serial_sequence('public.users', 'id'), COALESCE((SELECT MAX(id) FROM public.users), 1));\n\n`;

  // Categories
  for (const c of categories) {
    sql += `INSERT INTO public.categories (id, name) VALUES (${c.id}, ${sqlEscape(c.name)});\n`;
  }
  sql += `SELECT setval(pg_get_serial_sequence('public.categories', 'id'), COALESCE((SELECT MAX(id) FROM public.categories), 1));\n\n`;

  // Tasks
  for (const t of tasks) {
    sql += `INSERT INTO public.tasks (id, category_id, name, total_quantity, completed_quantity, progress_percent, unit, notes, is_manual) VALUES (${t.id}, ${sqlEscape(t.category_id)}, ${sqlEscape(t.name)}, ${sqlEscape(t.total_quantity)}, ${sqlEscape(t.completed_quantity)}, ${sqlEscape(t.progress_percent)}, ${sqlEscape(t.unit)}, ${sqlEscape(t.notes)}, ${sqlEscape(t.is_manual)});\n`;
  }
  sql += `SELECT setval(pg_get_serial_sequence('public.tasks', 'id'), COALESCE((SELECT MAX(id) FROM public.tasks), 1));\n\n`;

  // Sub units
  for (const s of sub_units) {
    sql += `INSERT INTO public.sub_units (id, task_id, serial_number, zone, code, status, total_quantity, notes, white_marked, white_extra, white_applied, white_date, brown_marked, brown_extra, brown_applied, brown_date) VALUES (${s.id}, ${sqlEscape(s.task_id)}, ${sqlEscape(s.serial_number)}, ${sqlEscape(s.zone)}, ${sqlEscape(s.code)}, ${sqlEscape(s.status)}, ${sqlEscape(s.total_quantity)}, ${sqlEscape(s.notes)}, ${sqlEscape(s.white_marked)}, ${sqlEscape(s.white_extra)}, ${sqlEscape(s.white_applied)}, ${sqlEscape(s.white_date)}, ${sqlEscape(s.brown_marked)}, ${sqlEscape(s.brown_extra)}, ${sqlEscape(s.brown_applied)}, ${sqlEscape(s.brown_date)});\n`;
  }
  sql += `SELECT setval(pg_get_serial_sequence('public.sub_units', 'id'), COALESCE((SELECT MAX(id) FROM public.sub_units), 1));\n\n`;

  // Marble distribution
  for (const m of marble_distribution) {
    sql += `INSERT INTO public.marble_distribution (id, zone, task_name, white_qty, brown_qty, status) VALUES (${m.id}, ${sqlEscape(m.zone)}, ${sqlEscape(m.task_name)}, ${sqlEscape(m.white_qty)}, ${sqlEscape(m.brown_qty)}, ${sqlEscape(m.status)});\n`;
  }
  sql += `SELECT setval(pg_get_serial_sequence('public.marble_distribution', 'id'), COALESCE((SELECT MAX(id) FROM public.marble_distribution), 1));\n\n`;

  // Daily updates
  for (const d of daily_updates) {
    sql += `INSERT INTO public.daily_updates (id, user_id, sender_name, sender_role, message_text, media_url, media_type, reply_to_id, created_at) VALUES (${d.id}, ${sqlEscape(d.user_id)}, ${sqlEscape(d.sender_name)}, ${sqlEscape(d.sender_role)}, ${sqlEscape(d.message_text)}, ${sqlEscape(d.media_url)}, ${sqlEscape(d.media_type)}, ${sqlEscape(d.reply_to_id)}, ${sqlEscape(d.created_at)});\n`;
  }
  sql += `SELECT setval(pg_get_serial_sequence('public.daily_updates', 'id'), COALESCE((SELECT MAX(id) FROM public.daily_updates), 1));\n\n`;

  // Materials consumption
  for (const mc of materials_consumption) {
    sql += `INSERT INTO public.materials_consumption (id, date, day, start_time, end_time, prepared_by, basics, marble, sealants, bulk, notes, created_at) VALUES (${sqlEscape(mc.id)}, ${sqlEscape(mc.date)}, ${sqlEscape(mc.day)}, ${sqlEscape(mc.start_time)}, ${sqlEscape(mc.end_time)}, ${sqlEscape(mc.prepared_by)}, ${sqlEscape(mc.basics)}, ${sqlEscape(mc.marble)}, ${sqlEscape(mc.sealants)}, ${sqlEscape(mc.bulk)}, ${sqlEscape(mc.notes)}, ${sqlEscape(mc.created_at)});\n`;
  }
  sql += `\n`;

  fs.writeFileSync('supabase_complete_backup.sql', sql, 'utf8');
  console.log('Export finished! File saved as supabase_complete_backup.sql');
}

exportAll().catch(err => console.error(err));
